objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>In Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bus</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BusGetter.cls
public with sharing class BusGetter {

    public static BusModel getBusFields(Id busId){
        if(CRUDandFLSChecker.checkObject('read', 'Bus__c')&&
           CRUDandFLSChecker.checkFields('read', 'Bus__c', new List<String>{'Name', 'Picture__c', 'Capacity__c', 'Status__c'})
          ){
            List<Bus__c> buses = [Select Name, Picture__c, Capacity__c, Status__c from Bus__c where Id = :busID limit 1];
            BusModel bm;
            if(buses.size() > 0){
            bm = new BusModel(buses[0].Name, buses[0].Picture__c, buses[0].Capacity__c, buses[0].Status__c);
			}
            return bm;
        }
        else {
            throw new System.NoAccessException();
        }
    }    
}