objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>In Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bus</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BusCounter.cls
public with sharing class BusCounter {

    public static Integer countAvailable(Id accountId){
        if(CRUDandFLSChecker.checkObject('read', 'Bus__c')&&
           CRUDandFLSChecker.checkFields('read', 'Bus__c', new List<String>{'Account__c', 'Status__c'})){
        	return [Select count() from Bus__c where (Account__c = :accountId and Status__c = 'Available')];
        }
        else{
            throw new insertException('You do not have a permission to access Buses');
        }
    }
    public static Integer countInUse(Id accountId){
        if(CRUDandFLSChecker.checkObject('read', 'Bus__c')&&
           CRUDandFLSChecker.checkFields('read', 'Bus__c', new List<String>{'Account__c', 'Status__c'})){
        	return [Select count() from Bus__c where (Account__c = :accountId and Status__c = 'In Use')];
        }
        else{
            throw new insertException('You do not have a permission to access Buses');
        }
    }
    
    @AuraEnabled
    public static Map<String, Integer> mapShow(Id accountId){
        Map<String, Integer> availabilityMap = new Map<String, Integer>();
        availabilityMap.put('available', countAvailable(accountId));
        availabilityMap.put('inuse', countInUse(accountId));
        return availabilityMap;
    }
}