objects/Bus__c.object
<CustomObject>
    <label>Bus</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusLine__c.object
<CustomObject>
    <fields>
        <fullName>Bus__c</fullName>
        <label>Bus</label>
        <referenceTo>Bus__c</referenceTo>
        <relationshipLabel>Lines</relationshipLabel>
        <relationshipName>Bus_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <referenceTo>Line__c</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Bus_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>BusLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line__c.object
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BusFormChecker.cls
public class BusFormChecker {
	
    public static void insertBusLine(Id busId, Id lineId){
        if(CRUDandFLSChecker.checkObject('create', 'BusLine__c')){
            try{
                BusLine__c busl = new BusLine__c(Bus__c = busId , Line__c = lineId);
                insert busl;
                }
            catch(DmlException e){
                throw new insertException('This bus is already attached to this line');
            }
        }
        else{
                throw new insertException('You do not have a permission to insert this object');
            }
        }    
    
    /*public static void deleteBusLine(Id busId, Id lineId){
        if(CRUDandFLSChecker.checkObject('delete', 'BusLine__c')){
                List<BusLine__c> buslinelist = [Select Id from BusLine__c where Bus__C =:busId and Line__C =:lineId];
                delete buslinelist;
        }
        else{
            throw new insertException('You do not have a permission to delete this object');
        }
    }*/
}