objects/Bus__c.object
<CustomObject>
    <label>Bus</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusLine__c.object
<CustomObject>
    <fields>
        <fullName>Bus__c</fullName>
        <label>Bus</label>
        <referenceTo>Bus__c</referenceTo>
        <relationshipLabel>Lines</relationshipLabel>
        <relationshipName>Bus_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <referenceTo>Line__c</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Bus_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>BusLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line__c.object
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeleteBusLineController.cls
public with sharing class DeleteBusLineController {
	
    @AuraEnabled
    public static void removeBusLine(Id busId, Id lineId){
        if(CRUDandFLSChecker.checkObject('read', 'BusLine__c') &&
           CRUDandFLSChecker.checkFields('read', 'BusLine__c', new List<String>{'Id', 'Bus__c', 'Line__c'}) &&
           CRUDandFLSChecker.checkObject('delete', 'BusLine__c')){
            List<BusLine__c> buslinelist = [Select Id from BusLine__c where (Bus__c = :busId and Line__c = :lineId)];
            delete buslinelist;
        }
        else {
            throw new AuraHandledException('You do not have a permission to remove Buses from Lines');
        }
    }
}