objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line__c.object
<CustomObject>
    <label>Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BusFormInfoGetter.cls
public with sharing class BusFormInfoGetter {
	
    public static Map<String, List<Object>> getInfoForForm(Id accountId){
        if(CRUDandFLSChecker.checkObject('read', 'Bus__c') &&
           CRUDandFLSChecker.checkObject('read', 'Line__c') &&
           CRUDandFLSChecker.checkFields('read', 'Bus__c', new List<String>{'Id', 'Name', 'Account__c'})&&
           CRUDandFLSChecker.checkFields('read', 'Line__c', new List<String>{'Id', 'Name'}))
        {
            Map<String, List<Object>> infoForForm = new Map<String, List<Object>>();
            List<BusModel> busList = new List<BusModel>();
            List<LineModel> lineList = new List<LineModel>();
            for(Bus__c bus : [Select Id, Name from Bus__c where Account__c= :accountId order by Name]){
                busList.add(new BusModel(bus.Id, bus.Name));
            }
            for(Line__c line : [Select Id, Name from Line__c order by Name]){
                lineList.add(new LineModel(line.Id, line.Name));
            }
            infoForForm.put('buses', busList);
            infoForForm.put('lines', lineList);
            return infoForForm;
        }
        else{
            throw new System.NoAccessException();
        }
    }
    
}