objects/Bus__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Buses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusLine__c.object
<CustomObject>
    <fields>
        <fullName>Bus__c</fullName>
        <label>Bus</label>
        <referenceTo>Bus__c</referenceTo>
        <relationshipLabel>Lines</relationshipLabel>
        <relationshipName>Bus_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line</label>
        <referenceTo>Line__c</referenceTo>
        <relationshipLabel>Buses</relationshipLabel>
        <relationshipName>Bus_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bus Line</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>BusLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bus Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Line__c.object
<CustomObject>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Point__c</fullName>
        <label>Start Point</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Line</label>
    <nameField>
        <label>Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BusLineMapGetter.cls
public with sharing class BusLineMapGetter {	
    
    public static Map<Id, List<LineModel>> getBusLineMap(Id accountID){
        if(CRUDandFLSChecker.checkObject('read', 'Bus__c')&&
           CRUDandFLSChecker.checkFields('read', 'Bus__c', new List<String>{'Id', 'Account__c'})&&
           CRUDandFLSChecker.checkObject('read', 'BusLine__c') &&
           CRUDandFLSChecker.checkFields('read', 'BusLine__c', new List<String>{'Line__c', 'Bus__c'}) &&
           CRUDandFLSChecker.checkObject('read', 'Line__c') &&
           CRUDandFLSChecker.checkFields('read', 'Line__c', new List<String>{'Id', 'Name', 'Start_Point__c', 'End_Point__c'})){
            Map<Id, List<LineModel>> BusLineMapGotByAccountId = new Map<Id, List<LineModel>>();
            List<BusModel> busList = new List<BusModel>();
            for (Bus__c bus : [SELECT Id  FROM Bus__c WHERE Account__c= :accountID]){
                busList.add(new BusModel(bus.Id));
			}
            for(BusModel bus : busList){
                List<LineModel> lineList = new List<LineModel>();
                List<BusLineModel> busLineList = new List<BusLineModel>();
                for(BusLine__c busLine :  [SELECT Line__c from BusLine__c where Bus__c = :bus.busId]){
                                                busLineList.add(new BusLineModel(busLine.Line__c));
                                            }
               List<id> lineIdList = new List<Id>();
               for(BusLineModel blm : busLineList){
                    lineIdList.add(blm.line);
               }
                for(Line__c line : [SELECT Id, Name, Start_Point__c, End_Point__c  from Line__c where Id in : lineIdList]){
                    lineList.add(new LineModel(line.Id, line.Name, line.Start_Point__c, line.End_Point__c));
                }
                BusLineMapGotByAccountId.put(bus.busId, lineList);
}
            return BusLineMapGotByAccountId;
        }
        else{
            throw new System.NoAccessException();
        }
    }
}